name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npx semantic-release
